name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from GitHub
      - uses: actions/checkout@v4

      # 2. Setup the .NET SDK (version 8.0.x ici)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Run unit tests (vous pouvez ignorer la couverture de code)
      - name: Run Unit tests
        working-directory: ./amel.aftisse.ObjectDetection.Tests
        run: dotnet test

      # 5. Publier le projet Web API en tant qu'exécutable autonome (Windows 10)
      - name: Publish Web API project
        run: dotnet publish ./amel.aftisse.ObjectDetection.WebApi/amel.aftisse.ObjectDetection.WebApi.csproj --self-contained true --output ./publish/win-x64 -c Release -r win-x64 /p:PublishSingleFile=true

      # 6. Télécharger l'artefact publié
      - name: Upload WebApp Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Publish win-x64 ObjectDetection
          path: ./publish/win-x64
