name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Run Unit test
        working-directory: ./amel.aftisse.ObjectDetection.Tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage/opencover.xml

      - name: Publish Web API project
        run: dotnet publish ./amel.aftisse.ObjectDetection.WebApi/amel.aftisse.ObjectDetection.WebApi.csproj --self-contained true --output ./publish/win-x64/ObjectDetection -c Release -r win-x64 /p:PublishSingleFile=true

      - name: Upload WebApp Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Publish win-x64 ObjectDetection
          path: ./win-x64/ObjectDetection
